### ISSUE TITLE
Implement readMessage?

### ISSUE THREAD

**Issue by Tiogaplanet** [sparkfun/SparkFun_MiP_Arduino_Library#3]
Hello.

Just trying to get Casey's attention or that of any contributor from Sparkfun (due to lack of messaging feature on github.com).  I'm having difficulty implementing a "readMessage" function - something to read data back from MiP.  Can anyone throw me a bone?

Thank you.

**Comment by ToniCorinne** [comment]
I'd take a look at the `int8_t MiP::sendMessage(unsigned char *message, uint8_t array_length){`function in MiP_commands.cpp. 
You can use this as a guideline for implementing a readMessage function. Make sure to update both the .cpp and .h files if you start writing new functions for the library.

**Comment by Tiogaplanet** [comment]
ToniCorinne,

I sincerely thank you for taking the time to help.  Do you receive notifications when 2stacks and I post comments to the pull request?

[https://github.com/sparkfun/SparkFun_MiP_Arduino_Library/pull/1](url)

I've tried doing what you're suggesting and I end up with results that only work occasionally.  I suspect I'm up against a timing issue but I'm not certain.

What did you guys do to implement that flamethrowing MiP??  Surely you had some part of your code that needed to read data back from the MiP, right?  Could you or a peer add that code to this library?

Thanks again for your help.

**Comment by ToniCorinne** [comment]
Unfortunately, I haven't been able to find an example of the sketch on the flamethrower. The engineer who originally worked on that no longer works at SparkFun, but I _believe_ he was simply triggering a pin high in order to light the flamethrower. The element would heat up and trigger the actual flame. 

As far as debugging the information coming back from the MiP, I'd recommend taking a look at the BLE examples the manufacturer has on their [GitHub](https://github.com/WowWeeLabs/MiP-BLE-Protocol) page. You could use that as a model for modifying the Arduino library for communication between the MiP and the AtMega328.

**Comment by Tiogaplanet** [comment]
@ToniCorinne I think I've got it figured out.  See the latest [commit ](https://github.com/Tiogaplanet/SparkFun_MiP_Arduino_Library/commit/c173ccd6615cb9931fe7efcd3b54251a44edd2fb) in my head.  Can you please accept the pull requests from 2stacks and me so I can create another pull request for the `getMessage` function?  I'd like to keep contributing to this library if you guys are interested.

**Comment by ToniCorinne** [comment]
Files have been merged. We'd love it if you'd like to keep contributing - it helps the community as a whole (which is the whole reason we put all of these files on GitHub). :)

**Comment by Tiogaplanet** [comment]
Thank you, @ToniCorinne!  I'll keep at it.  I'd love to see this library get fleshed out.
